apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: grafana
  annotations:
    openshift.io/display-name: grafana
    description: |-
             contra grafana template
    iconClass: icon-shadowman
    tags: instant-app,influxdb
    template.openshift.io/long-description: Grafana container
    template.openshift.io/provider-display-name: Red Hat, Inc.
    template.openshift.io/documentation-url: https://docs.openshift.org/latest
    template.openshift.io/support-url: https://access.redhat.com
parameters:
- name: STORAGE_SIZE
  value: 5Gi
  description: The size of the persistent storage for Grafana
- name: REPO_URL
  description: The repo url that contains the source. e.g. https://github.com/CentOS-PaaS-SIG/ci-pipeline.git
  value: https://github.com/CentOS-PaaS-SIG/contra-env-infra
  required: true
- name: REPO_CONTEXTDIR
  description: The sub-directory inside the repository. e.g. config/Dockerfiles/grafana
  value: grafana
  required: true
- name: REPO_REF
  description: The git ref or tag to use for customization.
  value: master
  required: true
- name: ADMIN_PASSWORD
  description: Password for the admin user
  value: "{{ grafana_admin_password }}"
  required: true
- name: ADMIN_USER
  description: admin username
  value: "{{ grafana_admin_user }}"
  required: true
- name: GRAFANA_INSTALL
  value: grafana-5.3.0-1.x86_64.rpm
  description: The grafana rpm
- name: NAMESPACE
  value: "{{ openshift_project }}"
- name: GF_AUTH_ANONYMOUS_ENABLED
  value: "true"
- name: INIT_DATASOURCE
  value: "true"
- name: INFLUXDB_ROUTE
  value: "{{ influxdb_api_route }}"
- name: INFLUXDB_PASSWORD
  value: "{{ influxdb_admin_password }}"
- name: INFLUXDB_USER
  value: "{{ influxdb_admin_user }}"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
    name: grafana
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: grafana
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: grafana:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: docker.io/contrainfra/grafana:latest
        env:
          - name: GRAFANA_INSTALL
            value: ${GRAFANA_INSTALL}
      type: Source
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grafana-lib
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${STORAGE_SIZE}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: grafana-log
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: ${STORAGE_SIZE}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      metrics: grafana
    name: grafana
  spec:
    ports:
    - name: grafana-web
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      metrics: grafana
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    creationTimestamp: null
    labels:
      metrics: grafana
    name: grafana
  spec:
    strategy:
      type: Recreate
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - grafana
        from:
          kind: ImageStreamTag
          name: grafana:latest
          namespace: ${NAMESPACE}
          lastTriggeredImage: ''
    - type: ConfigChange
    replicas: 1
    selector:
      metrics: grafana
    template:
      metadata:
        creationTimestamp: null
        labels:
          metrics: grafana
      spec:
        containers:
        - env:
          - name: INFLUXDB_HOST
            value: influxdb
          - name: GF_LOG_MODE
            value: console
          - name: GF_SECURITY_ADMIN_USER
            value: "${ADMIN_USER}"
          - name: GF_SECURITY_ADMIN_PASSWORD
            value: "${ADMIN_PASSWORD}"
          - name: GF_PATHS_PLUGINS
            value: /var/lib/grafana/plugins
          - name: GF_PATHS_DATA
            value: /var/lib/grafana/data
          - name: GF_USERS_ALLOW_SIGN_UP
            value: "true"
          - name: GF_AUTH_ANONYMOUS_ENABLED
            value: ${GF_AUTH_ANONYMOUS_ENABLED}
          - name: GF_AUTH_ANONYMOUS_ORG_NAME
            value: "Main Org."
          - name: GF_AUTH_ANONYMOUS_ORG_ROLE
            value: Viewer
          - name: INFLUXDB_ROUTE
            value: "${INFLUXDB_ROUTE}"
          - name: INFLUXDB_USER
            value: "${INFLUXDB_USER}"
          - name: INFLUXDB_PASSWORD
            value: "${INFLUXDB_PASSWORD}"
          - name: INIT_DATASOURCE
            value: "${INIT_DATASOURCE}"
          image: grafana:stable
          imagePullPolicy: Always
          name: grafana
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /login
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 2
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - containerPort: 3000
            protocol: TCP
          volumeMounts:
          - mountPath: /var/lib/grafana
            name: grafana-lib
          - mountPath: /var/log/grafana
            name: grafana-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        volumes:
        - name: grafana-lib
          persistentVolumeClaim:
            claimName: grafana-lib
        - name: grafana-log
          persistentVolumeClaim:
            claimName: grafana-log
  status: {}
- apiVersion: v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels:
      metrics: grafana
    name: grafana
  spec:
    port:
      targetPort: grafana-web
    to:
      kind: Service
      name: grafana
labels:
  template: grafana
